const ADD = 'ADD';
const EDIT = 'EDIT';
const REMOVE = 'REMOVE';
const LIST_RECIPES_SUCCESS = 'LIST_RECIPES_SUCCESS';
const LIST_RECIPES_STARTED = 'LIST_RECIPES_STARTED';
const LIST_RECIPES_FAILURE = 'LIST_RECIPES_FAILURE';

export {
  ADD,
  EDIT,
  REMOVE,
  LIST_RECIPES_SUCCESS,
  LIST_RECIPES_STARTED,
  LIST_RECIPES_FAILURE,
};
